### ISSUE TITLE
train.jsonl for foo101

### ISSUE THREAD

**Issue by mahdiabavisani** [facebookresearch/mmbt#1]
Downloaded `UPMC_Food101`, and trying to run the code for the `food101` experiment. It seems the code needs json files for the dataset (which is not provided by dataset itself).  How can I get them?

```
$ python mmbt/train.py --batch_sz 4 --gradient_accumulation_steps 40  --savedir mmbt/ --name mmbt_model_run  --data_path mmbt/data/  --task food101 --task_type classification  --model mmbt --num_image_embeds 3 --freeze_txt 5 --freeze_img 3   --patience 5 --dropout 0.1 --lr 5e-05 --warmup 0.1 --max_epochs 100 --seed 1
Traceback (most recent call last):
  File "mmbt/train.py", line 280, in <module>
    cli_main()
  File "mmbt/train.py", line 272, in cli_main
    train(args)
  File "mmbt/train.py", line 183, in train
    train_loader, val_loader, test_loaders = get_data_loaders(args)
  File "/home/fb/mmbt/data/helpers.py", line 113, in get_data_loaders
    os.path.join(args.data_path, args.task, "train.jsonl")
  File "/home/fb/mmbt/data/helpers.py", line 40, in get_labels_and_frequencies
    data_labels = [json.loads(line)["label"] for line in open(path)]
FileNotFoundError: [Errno 2] No such file or directory: 'mmbt/data/food101/train.jsonl'
```

**Comment by SeaOfOcean** [comment]
+1

**Comment by sebastianffx** [comment]
+1 
It would be great if authors can provide a script to build the datasets from the raw sources. 
Thanks anyway for the great work!

**Comment by pnnngchg** [comment]
+1
Got the same problem. Waiting for the script. Thanks a lot!

**Comment by apugoneappu** [comment]
+1
It would be great if the required format for the dataset could be detailed in the README.

**Comment by zhtsh** [comment]
+1
It would be great if authors can provide a script to build the datasets from the raw sources.

**Comment by suvrat96** [comment]
Hi everyone! I have added scripts for generating jsonl files for Food101 and MMIMDB datasets. Let me know if you run into any issues.

**Comment by fiona-lxd** [comment]
> Hi everyone! I have added scripts for generating jsonl files for Food101 and MMIMDB datasets. Let me know if you run into any issues.

Can you provide the URLs for downloading Food101 and MMIMDB dataset?

**Comment by douwekiela** [comment]
Sure:
- Food101: http://visiir.lip6.fr/data/public/UPMC_Food101.tar.gz (http://visiir.lip6.fr/)
- MMIMDB: http://lisi1.unal.edu.co/mmimdb/
