### ISSUE TITLE
Order of text and image embeddings concatenation does not match the comment

### ISSUE THREAD

**Issue by nishantvishwamitra** [facebookresearch/mmbt#2]
In the MultimodalBertEncoder, the text and image embeddings order of concatentation does not match the comment:

encoder_input = torch.cat([**img_embed_out, txt_embed_out**], 1)  # Bx(**TEXT+IMG**)xHID

**Comment by suvrat96** [comment]
Good catch, the comment should be (IMG+TEXT). 
We concatenate Images first as text was of variable length, while number of image embeddings is fixed.
