### ISSUE TITLE
Run on GQA dataset

### ISSUE THREAD

**Issue by yonatanbitton** [facebookresearch/mmbt#4]
Hello
Do you have an instructions to run MMBT on the GQA dataset?
I've tried to make changes in the repo but it doesn't seem to work.

I've tried to run with this CMD:
`python mmbt/train.py --batch_sz 4 --gradient_accumulation_steps 40 --savedir /users/yonatan/mmbt/savedir --name mmbt_model_run --data_path /users/yonatan/gqa_data_and_images_dir --task food101 --task_type classification --model mmbt --num_image_embeds 3 --freeze_txt 5 --freeze_img 3 --patience 5 --dropout 0.1 --lr 5e-05 --warmup 0.1 --max_epochs 100 --seed 1
`
Thank you

**Comment by douwekiela** [comment]
Hi, sorry I somehow missed this. I don't think the --task food101 argument is appropriate for GQA, unless you converted it to the food101 format?
